# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fa7a4f2f7b5f0e57df38dbf0d5867e5796390d92bd5ea09d48613a4fb270b1e72d5943d7e6e1573b9cabae2e95f6a946cfe47be85b31cf6fda338120c2468b6b

test:
  secret_key_base: bd5fe3a7818faaf76e972aa3becc4a23ba9bcbedd8ed5baef357bcbb604b2aece03316b5407e197dd9ae590713e57693e9e55acb0cd13ee8f64f75e405734c39

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
